"""SQLAlchemy table definitions — used by Alembic for migration autogeneration."""
from sqlalchemy import Column, Float, Index, Integer, MetaData, Table, Text, CheckConstraint

metadata = MetaData()

students = Table(
    "students", metadata,
    Column("student_id", Text, primary_key=True),
    Column("grade", Text),
    Column("display_name", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

learning_events = Table(
    "learning_events", metadata,
    Column("id", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("session_id", Text),
    Column("feature", Text, nullable=False),
    Column("event_type", Text, nullable=False),
    Column("grade", Text),
    Column("topic", Text),
    Column("lesson_id", Text),
    Column("book_id", Text),
    Column("score", Float),
    Column("success", Integer),
    Column("data_scope", Text, nullable=False, server_default="runtime"),
    Column("metadata_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("effect_key", Text),
    Index("idx_learning_events_student_created", "student_id", "created_at"),
    Index("idx_learning_events_scope_created", "data_scope", "created_at"),
    Index("idx_learning_events_feature_type_created", "feature", "event_type", "created_at"),
    Index("uq_learning_events_effect_key", "effect_key", unique=True),
)

student_profiles = Table(
    "student_profiles", metadata,
    Column("student_id", Text, primary_key=True),
    Column("grade", Text),
    Column("recent_topics_json", Text, nullable=False),
    Column("recent_lessons_json", Text, nullable=False),
    Column("weak_topics_json", Text, nullable=False),
    Column("strong_topics_json", Text, nullable=False),
    Column("quiz_stats_json", Text, nullable=False),
    Column("game_stats_json", Text, nullable=False),
    Column("character_interests_json", Text, nullable=False),
    Column("interaction_summary_json", Text, nullable=False, server_default="{}"),
    Column("updated_at", Text, nullable=False),
)

memory_entries = Table(
    "memory_entries", metadata,
    Column("id", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("type", Text, nullable=False),
    Column("content_json", Text, nullable=False),
    Column("source_feature", Text),
    Column("source_event_id", Text),
    Column("confidence", Float, nullable=False),
    Column("status", Text, nullable=False),
    Column("reason", Text),
    Column("metadata_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("last_used_at", Text),
    Column("disabled_at", Text),
    Column("deleted_at", Text),
    Index("idx_memory_entries_student_status", "student_id", "status", "updated_at"),
    Index("idx_memory_entries_source_event", "source_event_id"),
)

materials = Table(
    "materials", metadata,
    Column("material_id", Text, primary_key=True),
    Column("owner_key", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("filename", Text, nullable=False),
    Column("content_type", Text, nullable=False),
    Column("source_type", Text, nullable=False),
    Column("subject", Text),
    Column("grade", Text),
    Column("tags_json", Text, nullable=False),
    Column("text_chars", Integer, nullable=False),
    Column("page_count", Integer, nullable=False),
    Column("chunk_count", Integer, nullable=False),
    Column("ocr_mode", Text),
    Column("quality_json", Text),
    Column("warnings_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("expires_at", Text),
    Index("idx_materials_owner_created", "owner_key", "created_at"),
)

material_pages = Table(
    "material_pages", metadata,
    Column("id", Text, primary_key=True),
    Column("material_id", Text, nullable=False),
    Column("page_number", Integer, nullable=False),
    Column("source_type", Text, nullable=False),
    Column("text", Text, nullable=False),
)

material_chunks = Table(
    "material_chunks", metadata,
    Column("chunk_id", Text, primary_key=True),
    Column("material_id", Text, nullable=False),
    Column("owner_key", Text, nullable=False),
    Column("page_number", Integer, nullable=False),
    Column("text", Text, nullable=False),
    Column("metadata_json", Text, nullable=False),
    Index("idx_material_chunks_material", "material_id"),
    Index("idx_material_chunks_owner_material", "owner_key", "material_id"),
)

homework_reviews = Table(
    "homework_reviews", metadata,
    Column("id", Text, primary_key=True),
    Column("student_id", Text),
    Column("actor_id", Text),
    Column("grade_request_json", Text, nullable=False),
    Column("grade_result_json", Text, nullable=False),
    Column("needs_human_review", Integer, nullable=False, server_default="0"),
    Column("decision", Text, nullable=False, server_default="pending"),
    Column("teacher_id", Text),
    Column("teacher_note", Text),
    Column("teacher_score", Float),
    Column("created_at", Text, nullable=False),
    Column("reviewed_at", Text),
)

accounts = Table(
    "accounts", metadata,
    Column("actor_id", Text, primary_key=True),
    Column("username", Text, nullable=False, unique=True),
    Column("password_hash", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("display_name", Text),
    Column("created_at", Text, nullable=False),
    Column("account_status", Text, nullable=False, server_default="active"),
    Column("traffic_cohort", Text, nullable=False, server_default="unverified"),
    Column("updated_at", Text, nullable=False, server_default=""),
    CheckConstraint("role IN ('student','teacher','admin')", name="ck_accounts_role"),
    CheckConstraint("account_status IN ('active','disabled')", name="ck_accounts_status"),
    CheckConstraint("traffic_cohort IN ('demo','unverified','verified','operator')", name="ck_accounts_cohort"),
)

audit_events = Table(
    "audit_events", metadata,
    Column("id", Text, primary_key=True),
    Column("actor_id", Text),
    Column("action", Text, nullable=False),
    Column("resource_type", Text),
    Column("resource_id", Text),
    Column("success", Integer, nullable=False),
    Column("data_scope", Text, nullable=False, server_default="runtime"),
    Column("metadata_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Index("idx_audit_events_scope_created", "data_scope", "created_at"),
)

weakpoints = Table(
    "weakpoints", metadata,
    Column("student_id", Text, primary_key=True),
    Column("knowledge_tag", Text, primary_key=True),
    Column("wrong_count", Integer, nullable=False, server_default="1"),
    Column("last_wrong_at", Text, nullable=False),
    Column("source", Text, nullable=False),
    Column("correct_streak", Integer, nullable=False, server_default="0"),
    Index("idx_weakpoints_student", "student_id"),
)

weakpoint_evidence = Table(
    "weakpoint_evidence", metadata,
    Column("evidence_key", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("knowledge_tag", Text, nullable=False),
    Column("evidence_type", Text, nullable=False),
    Column("source_feature", Text, nullable=False),
    Column("source_session_id", Text),
    Column("assessment_id", Text),
    Column("evidence_stage", Text),
    Column("assessment_fingerprint", Text),
    Column("parent_evidence_key", Text),
    Column("eligible_at", Text),
    Column("occurred_at", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_weakpoint_evidence_student_tag_created", "student_id", "knowledge_tag", "created_at"),
    Index(
        "idx_weakpoint_evidence_chain",
        "student_id", "knowledge_tag", "evidence_stage", "assessment_fingerprint", "occurred_at",
    ),
)

review_mastery_state = Table(
    "review_mastery_state", metadata,
    Column("student_id", Text, primary_key=True),
    Column("knowledge_tag", Text, primary_key=True),
    Column("status", Text, nullable=False),
    Column("retrieval_evidence_key", Text),
    Column("verification_evidence_key", Text),
    Column("retention_evidence_key", Text),
    Column("retention_due_at", Text),
    Column("revision", Integer, nullable=False, server_default="0"),
    Column("updated_at", Text, nullable=False),
    Index("idx_review_mastery_due", "status", "retention_due_at"),
)

game_rounds = Table(
    "game_rounds", metadata,
    Column("round_id", Text, primary_key=True),
    Column("round_type", Text, nullable=False),
    Column("data", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Index("idx_game_rounds_type", "round_type"),
)

card_game_wrong_records = Table(
    "card_game_wrong_records", metadata,
    Column("student_key", Text, primary_key=True),
    Column("card_ids", Text, nullable=False),
)

card_game_reports = Table(
    "card_game_reports", metadata,
    Column("id", Text, primary_key=True),
    Column("student_key", Text, nullable=False),
    Column("data", Text, nullable=False),
    Index("idx_card_game_reports_key", "student_key"),
)

review_sessions = Table(
    "review_sessions", metadata,
    Column("id", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("date", Text, nullable=False),
    Column("tasks_json", Text, nullable=False),
    Column("completed", Integer, nullable=False, server_default="0"),
    Column("total", Integer, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("revision", Integer, nullable=False, server_default="0"),
    Column("status", Text, nullable=False, server_default="active"),
    Column("last_idempotency_key", Text),
    Column("last_request_hash", Text),
    Column("last_response_json", Text),
    Index("idx_review_sessions_student_date", "student_id", "date", unique=True),
)

assignments = Table(
    "assignments", metadata,
    Column("id", Text, primary_key=True),
    Column("teacher_id", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("subject", Text),
    Column("grade", Text),
    Column("questions_json", Text, nullable=False),
    Column("assignee_ids_json", Text, nullable=False),
    Column("due_date", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_assignments_teacher", "teacher_id", "created_at"),
)

assignment_submissions = Table(
    "assignment_submissions", metadata,
    Column("id", Text, primary_key=True),
    Column("assignment_id", Text, nullable=False),
    Column("student_id", Text, nullable=False),
    Column("answers_json", Text, nullable=False),
    Column("score", Float),
    Column("status", Text, nullable=False, server_default="submitted"),
    Column("submitted_at", Text, nullable=False),
    Column("teacher_feedback", Text),
    Column("reviewed_at", Text),
    Index("idx_assignment_submissions_assignment", "assignment_id"),
    Index("idx_assignment_submissions_student", "student_id", "assignment_id", unique=True),
)

agent_jobs = Table(
    "agent_jobs", metadata,
    Column("id", Text, primary_key=True),
    Column("job_type", Text, nullable=False),
    Column("actor_id", Text),
    Column("status", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
    Column("result_json", Text),
    Column("idempotency_key", Text),
    Column("trace_id", Text),
    Column("attempts", Integer, nullable=False, server_default="0"),
    Column("max_attempts", Integer, nullable=False, server_default="3"),
    Column("timeout_seconds", Integer, nullable=False, server_default="300"),
    Column("cancel_requested", Integer, nullable=False, server_default="0"),
    Column("error", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("started_at", Text),
    Column("finished_at", Text),
    Index("idx_agent_jobs_actor_idempotency", "actor_id", "idempotency_key", unique=True),
    Index("idx_agent_jobs_status_created", "status", "created_at"),
)

assistant_sessions = Table(
    "assistant_sessions", metadata,
    Column("session_id", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("title", Text),
    Column("status", Text, nullable=False),
    Column("source_feature", Text, nullable=False),
    Column("source_session_id", Text),
    Column("context_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_assistant_sessions_student_updated", "student_id", "updated_at"),
    Index("idx_assistant_sessions_source", "source_feature", "source_session_id"),
)

assistant_messages = Table(
    "assistant_messages", metadata,
    Column("message_id", Text, primary_key=True),
    Column("session_id", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("content", Text, nullable=False),
    Column("intent", Text),
    Column("trace_id", Text),
    Column("tool_results_json", Text, nullable=False),
    Column("metadata_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Index("idx_assistant_messages_session_created", "session_id", "created_at"),
)

student_notifications = Table(
    "student_notifications", metadata,
    Column("id", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("teacher_id", Text, nullable=False),
    Column("message", Text, nullable=False),
    Column("assignment_ids_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("read_at", Text),
    Index("idx_student_notifications_student", "student_id", "created_at"),
)

learning_preferences = Table(
    "learning_preferences", metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("student_id", Text, nullable=False, unique=True),
    Column("preferences_json", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

root_cause_records = Table(
    "root_cause_records", metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("student_id", Text, nullable=False),
    Column("knowledge_tag", Text, nullable=False),
    Column("question_text", Text),
    Column("student_answer", Text),
    Column("correct_answer", Text),
    Column("root_cause", Text, nullable=False),
    Column("confidence", Float, nullable=False),
    Column("analyzed_at", Text, nullable=False),
    Index("idx_root_cause_student_tag", "student_id", "knowledge_tag", "analyzed_at"),
)

autotutor_sessions = Table(
    "autotutor_sessions", metadata,
    Column("session_id", Text, primary_key=True),
    Column("student_id", Text, nullable=False),
    Column("trace_id", Text, nullable=False),
    Column("run_id", Text),
    Column("status", Text, nullable=False),
    Column("revision", Integer, nullable=False, server_default="0"),
    Column("state_json", Text, nullable=False),
    Column("inflight_idempotency_key", Text),
    Column("inflight_request_hash", Text),
    Column("start_idempotency_key", Text),
    Column("last_idempotency_key", Text),
    Column("last_request_hash", Text),
    Column("last_response_json", Text),
    Column("created_at", Float, nullable=False),
    Column("updated_at", Float, nullable=False),
    Index("idx_autotutor_sessions_student_updated", "student_id", "updated_at"),
    Index("idx_autotutor_sessions_run", "run_id"),
    Index("idx_autotutor_sessions_start_idempotency", "student_id", "start_idempotency_key", unique=True),
)

agent_runs = Table(
    "agent_runs", metadata,
    Column("run_id", Text, primary_key=True),
    Column("agent_type", Text, nullable=False),
    Column("actor_id", Text),
    Column("student_id", Text),
    Column("session_id", Text),
    Column("parent_run_id", Text),
    Column("durability_mode", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("revision", Integer, nullable=False, server_default="0"),
    Column("current_step_id", Text),
    Column("objective", Text, nullable=False),
    Column("context_refs_json", Text, nullable=False),
    Column("input_artifact_refs_json", Text, nullable=False),
    Column("plan_json", Text),
    Column("state_json", Text, nullable=False),
    Column("completion_json", Text),
    Column("budget_json", Text, nullable=False),
    Column("used_budget_json", Text, nullable=False),
    Column("config_version", Text, nullable=False),
    Column("trace_id", Text, nullable=False),
    Column("idempotency_scope", Text, nullable=False),
    Column("idempotency_key", Text),
    Column("last_event_sequence", Integer, nullable=False, server_default="0"),
    Column("expires_at", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("finished_at", Text),
    Index("uq_agent_runs_idempotency", "idempotency_scope", "idempotency_key", unique=True),
    Index("idx_agent_runs_session_created", "session_id", "created_at"),
    Index("idx_agent_runs_status_updated", "status", "updated_at"),
    Index("idx_agent_runs_agent_created", "agent_type", "created_at"),
    Index("idx_agent_runs_parent", "parent_run_id"),
)

agent_run_events = Table(
    "agent_run_events", metadata,
    Column("event_id", Text, primary_key=True),
    Column("run_id", Text, nullable=False),
    Column("sequence", Integer, nullable=False),
    Column("event_type", Text, nullable=False),
    Column("step_id", Text),
    Column("operation", Text),
    Column("status", Text, nullable=False),
    Column("public_payload_json", Text, nullable=False),
    Column("internal_metadata_json", Text, nullable=False),
    Column("data_scope", Text, nullable=False, server_default="runtime"),
    Column("created_at", Text, nullable=False),
    Index("uq_agent_run_events_sequence", "run_id", "sequence", unique=True),
    Index("idx_agent_run_events_run_created", "run_id", "created_at"),
    Index("idx_agent_run_events_scope_created", "data_scope", "created_at"),
)

agent_run_artifacts = Table(
    "agent_run_artifacts", metadata,
    Column("artifact_id", Text, primary_key=True),
    Column("run_id", Text, nullable=False),
    Column("owner_actor_id", Text),
    Column("student_id", Text),
    Column("artifact_type", Text, nullable=False),
    Column("sensitivity", Text, nullable=False),
    Column("content_json", Text, nullable=False),
    Column("content_sha256", Text, nullable=False),
    Column("expires_at", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_agent_artifacts_run", "run_id"),
    Index("idx_agent_artifacts_owner_created", "owner_actor_id", "created_at"),
    Index("idx_agent_artifacts_student_created", "student_id", "created_at"),
    Index("idx_agent_artifacts_expires", "expires_at"),
)

agent_checkpoints = Table(
    "agent_checkpoints", metadata,
    Column("checkpoint_id", Text, primary_key=True),
    Column("run_id", Text, nullable=False),
    Column("revision", Integer, nullable=False),
    Column("node_name", Text, nullable=False),
    Column("state_json", Text, nullable=False),
    Column("side_effect_ledger_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Index("idx_agent_checkpoints_run_revision", "run_id", "revision"),
)

agent_side_effects = Table(
    "agent_side_effects", metadata,
    Column("side_effect_id", Text, primary_key=True),
    Column("run_id", Text, nullable=False),
    Column("step_id", Text, nullable=False),
    Column("operation", Text, nullable=False),
    Column("idempotency_key", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("resource_ref", Text),
    Column("result_json", Text),
    Column("error_json", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("uq_agent_side_effects_run_key", "run_id", "idempotency_key", unique=True),
    Index("idx_agent_side_effects_run_step", "run_id", "step_id"),
    Index("idx_agent_side_effects_status_updated", "status", "updated_at"),
)

agent_rollout_observations = Table(
    "agent_rollout_observations", metadata,
    Column("observation_id", Text, primary_key=True),
    Column("agent_type", Text, nullable=False),
    Column("config_version", Text, nullable=False),
    Column("runtime_mode", Text, nullable=False),
    Column("deployed_commit", Text, nullable=False),
    Column("environment", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("latency_ms", Integer, nullable=False),
    Column("trace_id", Text),
    Column("data_scope", Text, nullable=False, server_default="runtime"),
    Column("traffic_cohort", Text, nullable=False, server_default="legacy_untrusted"),
    Column("rollout_eligible", Integer, nullable=False, server_default="0"),
    Column("eligibility_reason", Text, nullable=False, server_default="legacy_untrusted"),
    Column("created_at", Text, nullable=False),
    Index("idx_rollout_observation_slice_created", "agent_type", "config_version", "runtime_mode", "data_scope", "created_at"),
    Index("idx_rollout_observation_commit_created", "deployed_commit", "created_at"),
    Index("idx_rollout_observation_eligibility", "rollout_eligible", "eligibility_reason", "created_at"),
)

agent_release_evidence = Table(
    "agent_release_evidence", metadata,
    Column("evidence_id", Text, primary_key=True),
    Column("agent_type", Text, nullable=False),
    Column("config_version", Text, nullable=False),
    Column("runtime_mode", Text, nullable=False),
    Column("deployed_commit", Text, nullable=False),
    Column("environment", Text, nullable=False),
    Column("evidence_sha256", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Index("uq_agent_release_evidence_hash", "evidence_sha256", unique=True),
    Index("idx_release_evidence_slice_created", "agent_type", "config_version", "runtime_mode", "deployed_commit", "created_at"),
)

llm_capability_manifests = Table(
    "llm_capability_manifests", metadata,
    Column("manifest_id", Text, primary_key=True),
    Column("schema_version", Integer, nullable=False),
    Column("provider", Text, nullable=False),
    Column("environment", Text, nullable=False),
    Column("deployed_commit", Text, nullable=False),
    Column("image_digest", Text, nullable=False),
    Column("runtime_config_version", Text, nullable=False),
    Column("endpoint_fingerprint", Text, nullable=False),
    Column("manifest_sha256", Text, nullable=False),
    Column("generated_at", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Index("uq_llm_capability_manifest_hash", "manifest_sha256", unique=True),
    Index(
        "idx_llm_capability_manifest_provenance_expiry",
        "provider", "environment", "deployed_commit", "image_digest", "runtime_config_version",
        "endpoint_fingerprint", "expires_at",
    ),
)
